---
- name: Setup DHCP server
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install isc-dhcp-server
      apt:
        name: isc-dhcp-server
        state: present

    - name: Configure /etc/dhcp/dhcpd.conf
      lineinfile:
        path: /etc/dhcp/dhcpd.conf
        regexp: '^#?option domain-name-servers'
        line: 'option domain-name-servers 8.8.8.8;'

    - name: Ensure subnet 10.10.10.0/24 is defined
      blockinfile:
        path: /etc/dhcp/dhcpd.conf
        block: |
          subnet 10.10.10.0 netmask 255.255.255.0 {
            range 10.10.10.10 10.10.10.199;
            option routers 10.10.10.1;
          }

    - name: Set default-lease-time, max-lease-time, ddns-update-style
      blockinfile:
        path: /etc/dhcp/dhcpd.conf
        block: |
          default-lease-time 600;
          max-lease-time 7200;
          ddns-update-style none;

    - name: Restart isc-dhcp-server
      service:
        name: isc-dhcp-server
        state: restarted