---
# Use to create a container in Proxmox and set up a DHCP server inside it
- name: Setup DHCP server
  hosts: all
  become: true
  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install isc-dhcp-server
      apt:
        name: isc-dhcp-server
        state: present

    - name: Write dhcpd.conf with exact contents
      copy:
        dest: /etc/dhcp/dhcpd.conf
        content: |
          option domain-name-servers 8.8.8.8;
          subnet 10.10.10.0 netmask 255.255.255.0 {
            range 10.10.10.10 10.10.10.199;
            option routers 10.10.10.1;
          }
          default-lease-time 600;
          max-lease-time 7200;
          ddns-update-style none;
        mode: '0644'

